# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\ml64.exe
CU=clang
MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe
CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\link.exe
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\link.exe
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\link.exe

HelloAyan_CXXFLAGS=/EHsc -nologo -std:c++latest -Iinclude -Idep -Idep\fmt\include -Idep\optional\include -Idep\result\include -Idep\source_location\include -Idep\sol\include -Idep\pybind11\include
HelloAyan_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -libpath:build\windows\x64\release ayan.lib
ayan_CXXFLAGS=/EHsc -nologo -std:c++latest -Iinclude -Idep -Idep\fmt\include -Idep\optional\include -Idep\result\include -Idep\source_location\include -Idep\sol\include -Idep\pybind11\include
ayan_ARFLAGS=-nologo -machine:x64

default:  HelloAyan ayan

all:  HelloAyan ayan

.PHONY: default all  HelloAyan ayan

HelloAyan: build\windows\x64\release\HelloAyan.exe
build\windows\x64\release\HelloAyan.exe: build\windows\x64\release\ayan.lib build\.objs\HelloAyan\windows\x64\release\src\main.cpp.obj
	@echo linking.release HelloAyan.exe
	-@mkdir build\windows\x64\release > NUL 2>&1
	@"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe" $(HelloAyan_LDFLAGS) -out:build\windows\x64\release\HelloAyan.exe build\.objs\HelloAyan\windows\x64\release\src\main.cpp.obj > build/.build.log 2>&1

build\.objs\HelloAyan\windows\x64\release\src\main.cpp.obj: src\main.cpp
	@echo compiling.release src\main.cpp
	-@mkdir build\.objs\HelloAyan\windows\x64\release\src > NUL 2>&1
	@"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" -c $(HelloAyan_CXXFLAGS) -Fobuild\.objs\HelloAyan\windows\x64\release\src\main.cpp.obj src\main.cpp > build/.build.log 2>&1

ayan: build\windows\x64\release\ayan.lib
build\windows\x64\release\ayan.lib: build\.objs\ayan\windows\x64\release\src\core\logger.cpp.obj build\.objs\ayan\windows\x64\release\src\core\qmsg.cpp.obj
	@echo linking.release ayan.lib
	-@mkdir build\windows\x64\release > NUL 2>&1
	@"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe" -lib $(ayan_ARFLAGS) -out:build\windows\x64\release\ayan.lib build\.objs\ayan\windows\x64\release\src\core\logger.cpp.obj build\.objs\ayan\windows\x64\release\src\core\qmsg.cpp.obj > build/.build.log 2>&1

build\.objs\ayan\windows\x64\release\src\core\logger.cpp.obj: src\core\logger.cpp
	@echo compiling.release src\core\logger.cpp
	-@mkdir build\.objs\ayan\windows\x64\release\src\core > NUL 2>&1
	@"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" -c $(ayan_CXXFLAGS) -Fobuild\.objs\ayan\windows\x64\release\src\core\logger.cpp.obj src\core\logger.cpp > build/.build.log 2>&1

build\.objs\ayan\windows\x64\release\src\core\qmsg.cpp.obj: src\core\qmsg.cpp
	@echo compiling.release src\core\qmsg.cpp
	-@mkdir build\.objs\ayan\windows\x64\release\src\core > NUL 2>&1
	@"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" -c $(ayan_CXXFLAGS) -Fobuild\.objs\ayan\windows\x64\release\src\core\qmsg.cpp.obj src\core\qmsg.cpp > build/.build.log 2>&1

clean:  clean_HelloAyan clean_ayan

clean_HelloAyan:  clean_ayan
	@del /F /Q build\windows\x64\release\HelloAyan.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\HelloAyan.exe > NUL 2>&1
	@del /F /Q build\windows\x64\release\HelloAyan.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\HelloAyan.pdb > NUL 2>&1
	@del /F /Q build\.objs\HelloAyan\windows\x64\release\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\HelloAyan\windows\x64\release\src\main.cpp.obj > NUL 2>&1

clean_ayan: 
	@del /F /Q build\windows\x64\release\ayan.lib > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\ayan.lib > NUL 2>&1
	@del /F /Q build\windows\x64\release\ayan.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\ayan.pdb > NUL 2>&1
	@del /F /Q build\.objs\ayan\windows\x64\release\src\core\logger.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ayan\windows\x64\release\src\core\logger.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\ayan\windows\x64\release\src\core\qmsg.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ayan\windows\x64\release\src\core\qmsg.cpp.obj > NUL 2>&1

